#AndroidIDE: enforce UTF-8 & locale for Gradle daemon
#Wed Jan 21 06:29:02 GMT 2026
systemProp.user.language=en
systemProp.user.country=US
org.gradle.daemon=false
org.gradle.logging.level=quiet
org.gradle.jvmargs=-Xms1024M -Xmx1G -Dfile.encoding\=UTF-8 -Dconsole.encoding\=UTF-8
android.useAndroidX=true
kotlinVersion=2.4.20
enableGraalNative=false
systemProp.sun.jnu.encoding=UTF-8
graalHelperVersion=2.0.1
systemProp.file.encoding=UTF-8
org.gradle.configureondemand=false
android.enableR8.fullMode=false
gdxVersion=1.14.2
projectVersion=1.0.0
